[package]
name = "alloy"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2", features = ["full"] }
tokio = { version = "1.37", features = ["full", "test-util"] }
async-trait = "0.1"
thiserror = "1"
serde = "1"
serde_json = "1"
url = "2.1"